import { useEffect, useMemo, useRef, useState } from "react";
import { marked } from "marked";
import DOMPurify from "dompurify";
import { Toaster, toast } from "sonner";
import { ArrowLeft, ArrowRight, ChevronDown, ChevronUp, Download, Eye, FolderPlus, Loader2, Search, Trash2, X } from "lucide-react";
import { cn, formatSize } from "./lib/utils";
import { Button, IconButton } from "./components/ui/button";
import { Checkbox } from "./components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "./components/ui/dialog";

type FileItem = { name: string; size: number; modified: string };
type Listing = { files: FileItem[]; folders: string[]; usage: number };
type Item = (FileItem & { kind: "file" }) | { name: string; kind: "folder"; size: 0; modified: string };
const previewExt = new Set(["txt", "md", "markdown", "png", "jpg", "jpeg", "gif", "webp", "bmp", "svg", "mp4", "webm", "mov", "m4v", "ogv"]);
const ext = (name: string) => name.includes(".") ? name.split(".").pop()!.toLowerCase() : "";


export default function App() {
  const [path, setPath] = useState(""); const [listing, setListing] = useState<Listing>({ files: [], folders: [], usage: 0 });
  const [query, setQuery] = useState(""); const [sort, setSort] = useState<"name" | "size" | "modified">("name"); const [direction, setDirection] = useState<"asc" | "desc">("asc");
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10); const [selected, setSelected] = useState<Set<string>>(new Set());
  const [preview, setPreview] = useState<{ name: string; url: string; text?: string } | null>(null); const [mkdirOpen, setMkdirOpen] = useState(false); const [mkdirName, setMkdirName] = useState(""); const [uploading, setUploading] = useState(""); const [deleting, setDeleting] = useState<string | null>(null); const fileInput = useRef<HTMLInputElement>(null);
  const fullName = (name: string) => path ? `${path}/${name}` : name;
  const url = (name: string) => `/api/download?name=${encodeURIComponent(fullName(name))}`;
  const showError = (e: unknown) => toast.error(e instanceof Error ? e.message : "操作失败");
  async function load() { try { const response = await fetch(`/api/list?prefix=${encodeURIComponent(path)}`); const data = await response.json(); if (!response.ok) throw new Error(data.error || "读取文件列表失败"); setListing(data); setSelected(new Set()); } catch (e) { showError(e); } }
  useEffect(() => { void load(); }, [path]);
  const items = useMemo<Item[]>(() => { const keyword = query.trim().toLocaleLowerCase(); const folders: Item[] = listing.folders.filter(n => !keyword || n.toLocaleLowerCase().includes(keyword)).map(name => ({ name, kind: "folder", size: 0, modified: "" })); const files: Item[] = listing.files.filter(f => !keyword || f.name.toLocaleLowerCase().includes(keyword)).map(f => ({ ...f, kind: "file" })); const factor = direction === "asc" ? 1 : -1; return [...folders, ...files].sort((a,b) => { if (a.kind !== b.kind) return a.kind === "folder" ? -1 : 1; const av = sort === "name" ? a.name : sort === "size" ? a.size : Date.parse(a.modified) || 0; const bv = sort === "name" ? b.name : sort === "size" ? b.size : Date.parse(b.modified) || 0; return (typeof av === "string" ? av.localeCompare(bv as string, "zh-CN", { numeric: true }) : av - (bv as number)) * factor; }); }, [listing, query, sort, direction]);
  const pages = Math.max(1, Math.ceil(items.length / pageSize)); const visible = items.slice((Math.min(page, pages) - 1) * pageSize, Math.min(page, pages) * pageSize);
  function sortBy(key: typeof sort) { if (sort === key) setDirection(d => d === "asc" ? "desc" : "asc"); else { setSort(key); setDirection("asc"); } setPage(1); }
  async function remove(name: string) { setDeleting(name); try { const r = await fetch("/api/delete", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: fullName(name) }) }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || "删除失败"); await load(); } catch(e) { showError(e); } finally { setDeleting(null); } }
  async function upload(files: FileList | File[]) { for (const file of Array.from(files)) { try { setUploading(file.name); const r = await fetch("/api/upload-url", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: fullName(file.name) }) }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || `上传失败（HTTP ${r.status}）`); await new Promise<void>((resolve, reject) => { const xhr = new XMLHttpRequest(); xhr.open("PUT", d.url); xhr.upload.onprogress = e => e.lengthComputable && setUploading(`${file.name} · ${Math.round(e.loaded / e.total * 100)}%`); xhr.onload = () => xhr.status >= 200 && xhr.status < 300 ? resolve() : reject(new Error(`上传接口返回 HTTP ${xhr.status}`)); xhr.onerror = () => reject(new Error("上传网络错误")); xhr.send(file); }); } catch(e) { showError(e); } } setUploading(""); await load(); }
  async function openPreview(name: string) { const u = url(name); if (["png","jpg","jpeg","gif","webp","bmp","svg"].includes(ext(name)) || ["mp4","webm","mov","m4v","ogv"].includes(ext(name))) { setPreview({ name, url: u }); return; } try { const r = await fetch(u); if (!r.ok) throw new Error(`预览失败（HTTP ${r.status}）`); setPreview({ name, url: u, text: await r.text() }); } catch(e) { showError(e); } }
  async function mkdir() { const name = mkdirName.trim(); if (!/^[\u4e00-\u9fffA-Za-z0-9_-]{1,64}$/.test(name)) return toast.error("目录名只能使用中文、英文、数字、- 和 _"); try { const r = await fetch("/api/mkdir", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: fullName(name) }) }); const d=await r.json().catch(()=>({})); if (!r.ok) throw new Error(d.error || "创建目录失败"); setMkdirOpen(false); setMkdirName(""); await load(); } catch(e) { showError(e); } }
  async function batchDelete() { const names = [...selected]; if (!names.length || !confirm(`确认删除选中的 ${names.length} 个文件？`)) return; for (const name of names) await remove(name); }
  function batchDownload() { for (const name of [...selected]) { const a=document.createElement("a"); a.href=url(name); a.download=name; a.click(); } }
  return <div className="min-h-screen bg-[#fbfdf8] text-[#26332b]"><Toaster position="bottom-right" closeButton richColors />
    <main className="mx-auto flex h-screen max-w-5xl flex-col overflow-hidden px-4 py-4">
      <header className="flex shrink-0 items-center gap-3 pb-4"><a href="https://axe3.cn" target="_blank" rel="noreferrer" className="flex items-center gap-2 text-xl text-[#26332b] no-underline"><img src="/logo.svg" className="h-6 w-6"/>OSS 网盘</a></header>
      <section className="mb-4 flex h-16 shrink-0 cursor-pointer items-center justify-center rounded-xl border border-dashed border-[#b8cbb9] bg-white/60 text-sm shadow-sm" onClick={() => fileInput.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault(); if(e.dataTransfer.files) void upload(e.dataTransfer.files);}}><input ref={fileInput} hidden type="file" multiple onChange={e=>e.target.files && void upload(e.target.files)}/>{uploading || "点击或拖拽文件上传"}</section>
      <div className="mb-2 flex shrink-0 items-center gap-2"><button className="cursor-pointer px-1 text-sm text-[#5d8067] hover:text-[#376044]" onClick={()=>{setPath("");setPage(1)}}>{path || "根目录"}</button><div className="relative max-w-[280px] flex-1"><Search className="absolute left-2 top-2 h-4 w-4 text-[#8fa493]"/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="搜索当前目录" className="h-8 w-full rounded-md border border-[#cfdfd0] bg-[#fffffc] pl-8 pr-2 text-xs outline-none focus:border-[#8fb398]"/></div><span className="ml-auto whitespace-nowrap text-xs text-[#829488]">{formatSize(listing.usage)} / 500 GB</span><IconButton label="新建目录" onClick={()=>setMkdirOpen(true)}><FolderPlus className="h-4 w-4"/></IconButton><IconButton label="批量下载" disabled={!selected.size} onClick={batchDownload}><Download className="h-4 w-4"/></IconButton><IconButton label="批量删除" variant="destructive" disabled={!selected.size} onClick={()=>void batchDelete()}><Trash2 className="h-4 w-4"/></IconButton></div>
      <section className="min-h-0 flex-1 overflow-y-auto rounded-xl border border-[#dce7dc] bg-white shadow-sm" style={{scrollbarGutter:"stable"}}><div className="sticky top-0 z-10 grid grid-cols-[28px_minmax(0,1fr)_88px_145px_104px] border-b border-[#dce7dc] bg-[#f4f8f2] px-3 py-2 text-xs font-semibold text-[#68786c]"><span/><SortButton label="名称" active={sort === "name"} direction={direction} onClick={()=>sortBy("name")}/><SortButton label="大小" active={sort === "size"} direction={direction} onClick={()=>sortBy("size")}/><SortButton label="修改时间" active={sort === "modified"} direction={direction} onClick={()=>sortBy("modified")} className="hidden sm:flex"/><span/></div>{visible.map(item => item.kind === "folder" ? <div key={item.name} className="grid grid-cols-[28px_minmax(0,1fr)_88px_145px_104px] items-center border-b border-[#edf2ec] px-3 py-2 text-sm hover:bg-[#f3f8f1]" onClick={()=>{setPath(fullName(item.name));setPage(1)}}><span/><span className="truncate font-semibold text-[#4f7c5b]">📁 {item.name}</span><span/><span/><span/></div> : <div key={item.name} className="grid grid-cols-[28px_minmax(0,1fr)_88px_145px_104px] items-center border-b border-[#edf2ec] px-3 py-2 text-sm hover:bg-[#f3f8f1]" onClick={()=>location.href=url(item.name)}><span onClick={e=>e.stopPropagation()}><Checkbox checked={selected.has(item.name)} onCheckedChange={checked=>{const next=new Set(selected);checked?next.add(item.name):next.delete(item.name);setSelected(next)}}/></span><span className="truncate" title={item.name}>📄 {item.name}</span><span className="text-xs text-[#718c78]">{formatSize(item.size)}</span><span className="hidden text-xs text-[#718c78] sm:block">{new Date(item.modified).toLocaleString()}</span><span className="flex justify-end gap-1" onClick={e=>e.stopPropagation()}>{previewExt.has(ext(item.name))&&<IconButton label="预览" onClick={()=>void openPreview(item.name)}><Eye className="h-4 w-4"/></IconButton>}<IconButton label="下载" onClick={()=>location.href=url(item.name)}><Download className="h-4 w-4"/></IconButton><IconButton label="删除" variant="destructive" disabled={deleting===item.name} onClick={()=>void remove(item.name)}>{deleting===item.name?<Loader2 className="h-4 w-4 animate-spin"/>:<Trash2 className="h-4 w-4"/>}</IconButton></span></div>)}</section>
      <footer className="flex shrink-0 items-center justify-center gap-3 pt-3"><Select value={String(pageSize)} onValueChange={value=>{setPageSize(Number(value));setPage(1)}}><SelectTrigger aria-label="每页数量"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="10">10 条/页</SelectItem><SelectItem value="30">30 条/页</SelectItem><SelectItem value="50">50 条/页</SelectItem></SelectContent></Select><IconButton label="上一页" disabled={page<=1} onClick={()=>setPage(page-1)}><ArrowLeft className="h-4 w-4"/></IconButton><span className="min-w-24 text-center text-xs text-[#718c78]">{Math.min(page,pages)} / {pages} · 共 {items.length} 项</span><IconButton label="下一页" disabled={page>=pages} onClick={()=>setPage(page+1)}><ArrowRight className="h-4 w-4"/></IconButton></footer>
    </main><Dialog open={mkdirOpen} onOpenChange={setMkdirOpen}><DialogContent><DialogHeader><DialogTitle>新建目录</DialogTitle><DialogDescription>仅支持中文、英文、数字、- 和 _</DialogDescription></DialogHeader><input autoFocus value={mkdirName} onChange={e=>setMkdirName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void mkdir()} placeholder="输入目录名称" className="h-9 w-full rounded-md border border-[#cfdfd0] px-3 text-sm outline-none focus:ring-2 focus:ring-[#dcecdc]"/><div className="flex justify-end gap-2"><Button variant="ghost" onClick={()=>setMkdirOpen(false)}>取消</Button><Button onClick={()=>void mkdir()}>创建</Button></div></DialogContent></Dialog>{preview&&<PreviewDialog data={preview} onClose={()=>setPreview(null)}/>}</div>;
}
function SortButton({label,active,direction,onClick,className}: {label:string;active:boolean;direction:"asc"|"desc";onClick:()=>void;className?:string}) { return <button type="button" className={cn("flex items-center gap-1 bg-transparent p-0 text-left text-xs font-semibold text-[#68786c] outline-none",className)} onClick={onClick}><span>{label}</span><span className={active?"text-[#5f8969]":"text-[#aab7ac]"}>{active?(direction==="asc"?<ChevronUp className="h-3 w-3"/>:<ChevronDown className="h-3 w-3"/>):<span className="flex"><ChevronUp className="h-2.5 w-2.5"/><ChevronDown className="-ml-2 h-2.5 w-2.5"/></span>}</span></button>; }
function PreviewDialog({data,onClose}: {data:{name:string;url:string;text?:string};onClose:()=>void}) { const e=ext(data.name); return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="flex max-h-[90vh] max-w-4xl flex-col overflow-hidden p-0"><DialogHeader className="border-b p-3"><DialogTitle className="truncate pr-6 text-sm font-medium">{data.name}</DialogTitle></DialogHeader><div className="overflow-auto p-4">{["png","jpg","jpeg","gif","webp","bmp","svg"].includes(e)&&<img src={data.url} className="mx-auto max-h-[70vh] max-w-full"/>}{["mp4","webm","mov","m4v","ogv"].includes(e)&&<video src={data.url} controls className="mx-auto max-h-[70vh] max-w-full"/>}{data.text!==undefined&&(e==="md"||e==="markdown"?<article className="prose max-w-none" dangerouslySetInnerHTML={{__html:DOMPurify.sanitize(marked.parse(data.text) as string)}}/>:<pre className="whitespace-pre-wrap break-words text-sm">{data.text}</pre>)}</div></DialogContent></Dialog>; }
